### ISSUE TITLE
SQL data copying can be done in parallel

### ISSUE THREAD

**Issue by JoshCu** [JoshCu/NGIAB_data_preprocess#10]
during the subset step, we essentially do this
for table in database:
    get_info(table)
for table in info:
    write_to_new_database(table)

the reads can be done in parallel, possibly the writes too.

**Comment by chp2001** [comment]
Prototyped in commit [6169b90](https://github.com/JoshCu/NGIAB_data_preprocess/commit/6169b902c2f3c6f04b7a0e008791d9e23b95b890)
Benchmarked as about 1 second time save per subset operation.

**Comment by JoshCu** [comment]
For larger operations it might save more but I'm suspicious that it's 80% of the way to being IO bound anyway. I'll close this and we can revisit it later if needed.
